# Generated by Django 5.1 on 2024-08-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='value', max_length=255)),
                ('f_nam', models.CharField(default='value', max_length=44)),
                ('staff', models.CharField(max_length=44)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icons/')),
                ('title', models.CharField(max_length=55)),
                ('deteil', models.TextField()),
                ('is_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
